name: Update avatar on Slack

on:
  workflow_dispatch:
  schedule:
    # every 10th minute
    - cron: '*/10 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout slack-abstract
        uses: actions/checkout@v2
        with:
          repository: mpolyak/slack-abstract
          path: slack-abstract

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: slack-abstract/package-lock.json

      - name: Install Node.js dependencies
        if: steps.setup-node.outputs.cache-hit != 'true'
        run: npm install
        working-directory: slack-abstract

      - name: Compute next run number
        run: echo "NEXT_RUN_NUMBER=$(expr ${{ github.run_number }} + 1)" >> $GITHUB_ENV

      - name: Get game.save from cache
        uses: actions/cache@v2
        with:
          path: game.save
          key: game-${{ github.run_number }}
          restore-keys: |
            game-

      - name: Update avatar on Slack
        run: npm start
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SAVE_GAME: ../game.save
        working-directory: slack-abstract

      - name: Cache game.save for next run
        uses: actions/cache@v2
        with:
          path: game.save
          key: game-${{ env.NEXT_RUN_NUMBER }}
